name: Build-Sync-Preview

# the workflow will be called by others
on:
  workflow_call:
    inputs:
      doc-repo:
        required: true
        type: string
      doc-url:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  Build-Site-Preview:
    # The type of runner that the job will run on
    runs-on: [self-hosted, doc-build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the full site with preview branch
        run: |
          cd ${{ runner.temp }}
          mkdir -p DocHome
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/${{ inputs.doc-repo }}.git ${{ inputs.doc-repo }}
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo
          cp -rfp ./${{ inputs.doc-repo }}/* ./DocHome/
          cp -rfp ./Docs-Template-Repo/* ./DocHome/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" ${{ runner.temp }}/DocHome/_config.yml
          cd DocHome && bundle install && bundle exec jekyll build

      - name: 'Create Tar files'
        run: tar -czvf ${{ inputs.doc-repo }}.tar.gz -C ${{ runner.temp }}/DocHome/_site .

      - name: Upload the built site as a single artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ inputs.doc-repo }}
          path: ${{ inputs.doc-repo }}.tar.gz
          retention-days: 2

  Sync-To-Testing:
    # The type of runner that the job will run on
    runs-on: [self-hosted, upload-test]
    needs: Build-Site-Preview

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Download the artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: ${{ inputs.doc-repo }}

      - name: 'Extract Tar files'
        shell: cmd
        run: |
          mkdir ${{ runner.temp }}\DocHome\_site
          tar -xzf ${{ inputs.doc-repo }}.tar.gz -C ${{ runner.temp }}\DocHome\_site

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          protocol: ftps
          port: 2122
          local-dir: ${{ runner.temp }}\DocHome\_site/
          server-dir: /www.dynamsoft.com/${{ inputs.doc-url }}/